// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iiits_face_recognition_core.Models;

#nullable disable

namespace iiits_face_recognition_core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241110055129_AddRecognizedPerson")]
    partial class AddRecognizedPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iiits_face_recognition_core.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo1Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo2Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("iiits_face_recognition_core.Models.RecognizedPerson", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CapturedPhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecognizedPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("double precision");

                    b.Property<byte[]>("UnknownEmbedding")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.ToTable("RecognizedPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
